### PR TITLE
Migrate to Polymer 0.8

### PR DESCRIPTION
**Pull request by kant2002**

### CODE REVIEW

**Comment by MetaMemoryT** [comment]
:+1: good work!

**Comment by MetaMemoryT** [comment]
@addyosmani @ebidel could this code be merged in a new repo PolymerElements/paper-progress and be tagged v0.8.0?

**Comment by notwaldorf** [comment]
I think porting this is a little more complicated, since it depends on porting `core-range` first (none of the 0.8 elements should depend on 0.5 ones). I think @blasten has started working on both, so maybe he can chime in?

**Comment by MetaMemoryT** [comment]
core-range has also been updated by @kant2002 see: https://github.com/Polymer/core-range/pull/7

**Comment by blasten** [comment]
@MetaMemoryT  I ported ``iron-range`` to 0.8, but I realized that ``paper-progress`` extends ``iron-range``. So iron-range should be a behavior if we want to keep it standalone. Is there a use case for that @notwaldorf or @cdata ?  Otherwise I would think that ``paper-progress`` and ``iron-range`` should be merged.
https://github.com/PolymerElements/iron-range/tree/0.8

**Comment by cdata** [comment]
Yeah, `iron-range` should probably be a behavior. Maybe call it
`iron-range-behavior`? I think that is our convention for naming behaviors
now.

**Comment by blasten** [comment]
@cdata good to know!  Is there anyone planning to work on ``paper-progress``?

**Comment by notwaldorf** [comment]
I'm going to close this, since `paper-slider` and `paper-progress` have been ported.

**Pull request closed without merging**
